### ISSUE TITLE
Catalog deletion failure returns as success

### ISSUE THREAD

**Issue by dhruvpatelaj** [vmware/terraform-provider-vcd#696] opened 2021-07-19 19:55 UTC
Hi there,

The scenario where the bug occurs is when I create a vcd_catalog and upload a local ovf file using vcd_catalog_item. Lets say for whatever reason, kernel dies or you manually (ctrl + c). The file is still uploading. Currently my script calls `terraform destroy` before any actions to remove any existing code. 

So if the file is still uploading, the terraform destroy call will try to delete the catalog. VCD will fail in deleting that catalog as there is a pending template upload, but terraform will return it as deleted. So, now the catalog still exists in VCD, but it no longer exists in terraform .tfstate. Therefore, we would have to manually go and delete the catalog.

The only way to work around this is to let the file upload finish. Should terraform not fail to delete the catalog too?

### Terraform Version
Terraform v1.0.2

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_catalog
- vcd_catalog_item

### Expected Behavior
Terraform should have returned `failed to delete catalog`

### Actual Behavior
Terraform succeeded in deleting catalog, but in actuality, VCD denied the request as there was a pending ovf file uploading within the catalog

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. wait until OVF file starts uploading. Basically until after the catalog is created.
2. `ctrl + c`
3. `terraform destroy` before OVF file has finished uploading

**Comment by dataclouder** [comment] 2021-07-19 20:10
Thanks for this clear report.
I will try to reproduce. The described behavior should not happen.

**Comment by dhruvpatelaj** [comment] 2021-07-23 16:35
Were you able to replicate?

**Comment by dataclouder** [comment] 2021-07-25 07:55
Reproduced by using this sequence of events:
1. add a catalog
2. add a catalog item
3. run `terraform state rm vcd_catalog_item.$catalog_item_name`
4. run `terraform destroy`

The destruction operation succeeds, but the catalog (and its item) remain in place.

**Comment by dataclouder** [comment] 2021-07-29 03:45
The behavior is fixed in PR #698.
* Starting the `destroy` while the catalog item is still being imported, the catalog deletion now fails because a catalog object is busy with another operation (just like in the web interface);
* Starting the `destroy` when the catalog item has been fully imported, and both `delete_force` and `delete_recursive` were set, the deletion will succeed

**Closed** 2021-08-06 07:45 UTC
