### ISSUE TITLE
Modifying the above_rule_id property of a firewall rule results in replacement of all resources

### ISSUE THREAD

**Issue by GeorgiosGoniotakis** [vmware/terraform-provider-vcd#625] opened 2021-01-13 16:35 UTC
### Details
Terraform Version: 0.14.4

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_nsxv_firewall_rule

### Description of Issue
Hello there and thank you for your contribution to open source. We are currently using the property `above_rule_id` mentioned on Example no 4 of the docs for `vcd_nsxv_firewall_rule`. 

```hcl
resource "vcd_nsxv_firewall_rule" "my-rule-1" {
  org          = "my-org"
  vdc          = "my-vdc"
  edge_gateway = "my-edge-gateway"

  logging_enabled = "true"
  action          = "deny"

  source {
    ip_addresses = ["30.10.10.0/24", "31.10.10.0/24"]
    org_networks = ["org-net-1", "org-net-2"]
  }

  destination {
    ip_addresses = ["any"]
  }

  service {
    protocol = "icmp"
  }
}

resource "vcd_nsxv_firewall_rule" "my-rule-2" {
  org          = "my-org"
  vdc          = "my-vdc"
  edge_gateway = "my-edge-gateway"

  # This attribute allows to ensure rule is inserted above the referred one
  # in rule processing engine
  above_rule_id = "${vcd_nsxv_firewall_rule.my-rule-1.id}"
  name          = "my-friendly-name"

  source {
    ip_addresses = ["30.10.10.0/24", "31.10.10.0/24"]
    org_networks = ["org-net-1", "org-net-2"]
  }

  destination {
    ip_addresses = ["any"]
  }

  service {
    protocol = "icmp"
  }
}
```

We have created a chain of about 30 rules which use the `above_rule_id` property to create a prioritized list. We are facing the issue that if we need to remove a resource (rule) all of the resources have to be replaced (destroyed and re-created). What would be a way to add or remove a firewall rule without having to re-create all the rules of the set? At this stage we are still experimenting so we could potentially restructure our Terraform code in order to fulfil this requirement. Any guidance would be much appreciated.

**Comment by Didainius** [comment] 2021-01-14 07:20
By reading through it looks like this is a duplicate of #624.
Feel free to reopen if this is something else.

**Closed by Didainius** 2021-01-14 07:20 UTC

**Comment by GeorgiosGoniotakis** [comment] 2021-01-14 07:31
Hello @Didainius it's indeed the same issue. It was created by mistake.
