### ISSUE TITLE
Report "Error: error retrieving Org and VDC " when creating more than 10 VMs

### ISSUE THREAD

**Issue by darcyllingyan** [vmware/terraform-provider-vcd#642] opened 2021-02-22 09:33 UTC
When using terraform to create VMs(11 VMs) with parallelism =10, it reports below error, after changed the parallelism=7, the 11 VMs create succeed, want to confirm whether the parameter impact the number of VMs creationg

2021-02-22 06:03:47,355 DEBUG: Error: error retrieving Org and VDC: error retrieving VDC: error retrieving VDC: Get "https://<ip address>/api/vdc/<resource id>": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021-02-22 06:03:47,355 DEBUG:
2021-02-22 06:03:47,355 DEBUG:   on modules/instance/test/group_01/main.tf line 77, in resource "vcd_independent_disk" "volume-02":
2021-02-22 06:03:47,355 DEBUG:   77: resource "vcd_independent_disk"  "volume-02" {
2021-02-22 06:03:47,355 DEBUG:
2021-02-22 06:03:47,355 DEBUG:
2021-02-22 06:03:51,482  INFO:

**Comment by Didainius** [comment] 2021-02-22 09:43
Hello @darcyllingyan ,
This error looks to be self explanatory and I'd at first have a look if your VCD instance (or load balancer in front) can cope with this load. `Client.Timeout exceeded while awaiting headers` basically tells that it timed out waiting for response.

**Comment by darcyllingyan** [comment] 2021-02-23 02:32
Hi @Didainius ,
Thanks for the response, the error occurs occasional, suppose the probability is about 30%.
It's useless if I increase the max_retry_timeout.

How to check whether the VCD instance can cope with this load?

Thanks

**Comment by Didainius** [comment] 2021-02-23 06:04
@darcyllingyan ,


>     1. How to check whether the VCD instance can cope with this load? The VCD instance resource is sufficient for these VMs.

Getting timeouts is a very good chance it can not cope with the load. You might as well turn on logging to get additional log from SDK (https://registry.terraform.io/providers/vmware/vcd/latest/docs#logging). That should show all API calls and might show which exact call and how long it takes before it times out.



>     2\. The parallelism value defination is determined by the VCD instance load? When the load is smaller, the parallelism value should be smaller?  Whether it has dependency?

This is very specific. It even depends on what tasks you perform. I'd imagine some simple tasks wouldn't cause much trouble, but spawning a lot of VMs (where it clones huge VM image) can jam the system. But again - this is very specific and hard to get to it. 


The instance you mentioned always gets this timeout - is it built according to VCD spec requirements or is it a lab? That could give more hints. As it stands now the timeouts are pretty big in the provider so that must be surely a problem if you are hitting them. The additional logging I mentioned should allow to see a bit better what time does it take to get responses from API.

These are the timeouts we are currently using:

<img width="875" alt="image" src="https://user-images.githubusercontent.com/15804230/108807512-56bdbf80-75ad-11eb-954d-f44e0633c8f5.png">

**Comment by darcyllingyan** [comment] 2021-02-23 08:48
Hi @Didainius ,
Thanks for the response. 
I turnned on the logging to get additional log, but it's strange I didn't find any error information and all the response shows "Response status 2xx", whether it is caused that the **Timeout: 600 * time.Second** is smaller for more VM creation tasks?
As seems the client and server response and request messages are normal,  over 600s the VMs aren't created vi /optcompletely, the terraform exit the procedure.

After check the terraform creation log, after 10m10s(over 600s), the independent_disk is still creating.
  
```
2021-02-23 01:54:43,094 DEBUG: module.test-wrk-08.vcd_independent_disk.volume-01: Still creating... [10m10s elapsed]
```

**Comment by Didainius** [comment] 2021-02-23 09:05
@darcyllingyan ,
The timeout is for single API call. There are hundreds of API calls going on, even a single object creation (for long running operations we track "task state" by querying its  state). 

What I would look for is in `go-vcloud-director.log` you should see an API request record (most probbaly the last call in the file, but not necessarily) and then there will be this timeout error. (it can probably be in Terraform debug log `TF_LOG=DEBUG`) as well as your console. 


That could probably hint the time difference between request and the timeout itself. For experimentation purposes I could make a fork for you to test with even bigger timeouts, but if that is really hitting 600s for single API call, then probably VCD performance must be looked at or parallelism decreased.

**Comment by mindenNEVfoglalt** [comment] 2021-03-10 11:41
I'm also struggling with deployments failing with _Client.Timeout exceeded while awaiting headers_ issues.

These happen at random API calls, like get networkConfigSection, get task or get VDC.

When VCD_API_LOGGING is enabled, the request call can be seen in the log, and then 10 minute silence.

In this example TF failed with this error:
`2021-03-10 09:21:59,244 DEBUG: Error: error completing tasks: error retrieving task: error retrieving task: Get "https:///api/task/81e61a9d-5462-4f04-868e-57c31b027bc7": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

In the API log the WaitTaskCompletion request can be seen, that went unanswered by vCloud Director, then 10 minute silence and then a different request.
```
2021/03/10 09:00:12 --------------------------------------------------------------------------------
2021/03/10 09:00:12 Request caller: govcd.(*Task).WaitTaskCompletion-->govcd.(*Task).WaitTaskCompletion-->govcd.(*Task).WaitInspectTaskCompletion-->govcd.(*Task).Refresh-->govcd.(*Client).newRequest
2021/03/10 09:00:12 GET https:///api/task/81e61a9d-5462-4f04-868e-57c31b027bc7
2021/03/10 09:00:12 --------------------------------------------------------------------------------
2021/03/10 09:00:12 Req header:
2021/03/10 09:00:12 	X-Vcloud-Authorization: [********]
2021/03/10 09:00:12 	Accept: [application/*+xml;version=31.0]
2021/03/10 09:10:12 --------------------------------------------------------------------------------
2021/03/10 09:10:12 Request caller: govcd.getOrgHREF-->govcd.executeRequestWithApiVersion-->govcd.executeRequestWithApiVersion-->govcd.executeRequestCustomErr-->govcd.(*Client).NewRequestWithApiVersion-->govcd.(*Client).newRequest
2021/03/10 09:10:12 GET https:///api/org
2021/03/10 09:10:12 --------------------------------------------------------------------------------
2021/03/10 09:10:12 Req header:
2021/03/10 09:10:12 	X-Vcloud-Authorization: [********]
2021/03/10 09:10:12 	Accept: [application/*+xml;version=31.0]
2021/03/10 09:10:12 ################################################################################
2021/03/10 09:10:12 Response caller vcd.resourceVcdVAppVmCreate-->vcd.(*VCDClient).GetOrgAndVdcFromResource-->vcd.(*VCDClient).GetOrgAndVdc-->govcd.(*VCDClient).GetOrgByName-->govcd.getOrgHREF-->govcd.(*Client).executeRequest-->govcd.decodeBody
2021/03/10 09:10:12 Response status 200 OK
2021/03/10 09:10:12 ################################################################################
...
```
I understand it is not terraform-provider-vcd's fault that is is not getting a response from vCloud Director, and agree with that it's most likely the vCD being jammed, or the load balancer even.

Unfortunately these Client.Timeouts frequently occur even with parallelism=1 in my case. Also tried to increase VCD_MAX_RETRY_TIMEOUT to 1200 to no avail, I think this has no effect in this case.

Counting the request callers in the API log, in average 4.8 API calls were sent to vCloud Director per second, before the timeout happened.

I think it would be great if terraform-provider-vcd would tolerate occasional no response from vCD.

On the other hand, is there a way to to limit or just further decrease the number of API calls/sec sent to vCD?

**Comment by mindenNEVfoglalt** [comment] 2021-03-19 08:54
Please disregard my comment about limiting the API calls/sec sent to vCD.

During further analysis the following were found:
* these occasional Client.Timeouts still happen even if vCloud cell and Terraform are in the same L2 network
* the unanswered API call does not reach the vCloud cell based on its request.log
* the unanswered API calI (marked) is seen in a TCP stream which is already being torn down:
![SNAG-210317-103638-05](https://user-images.githubusercontent.com/34750791/111752370-e6494c00-8895-11eb-9840-555c60947464.png)

The network trace and [this article](https://medium.com/@p408865/til-go-http-client-reuse-connection-5d8c48731dec) makes me believe the root cause is around HTTP keep-alive, and probably in go-vcloud-director.

**Comment by Didainius** [comment] 2021-03-22 08:32
@mindenNEVfoglalt ,
Thanks for this investigation. Looking at your article - it looks that for proving/seeing if it helps we could try to set `DisableKeepAlives` to `true`. I could make a fork of it - would you be open to try this out just for seeing what is going on in there and if it helps. I don't think this would be a good permanent solution, but might just give us some clue.

**Comment by mindenNEVfoglalt** [comment] 2021-03-22 10:08
Hello @Didainius, I'd really appreciate such fork, so I could confirm or deny this theory.

**Comment by Didainius** [comment] 2021-03-22 10:33
@mindenNEVfoglalt ,
Here is the branch with go-vcloud-director HTTP client having this setting:
https://github.com/Didainius/terraform-provider-vcd/tree/issue-642-disablekeepalive

Are you able to build Terraform provider from source or should I build and host it somewhere for you?

![image](https://user-images.githubusercontent.com/15804230/111976816-b9519f00-8b0a-11eb-87c5-4548d4050376.png)

**Comment by kisstd** [comment] 2021-04-22 09:38
Apologies for not coming back on this earlier, this issue took an unexpected turn.

First, I neglected to mention it was terraform-provider-vcd v2.9.0 where we observed this problem, and we could not easily upgrade, because of relying on Python code creating the .tf plan. That .tf file is no longer compatible with terraform-provider-vcd v3.0.0 and above, and we had no possibility to refactor the .tf generation code.

My colleague, who didn't wish to be named, was kind enough to build terraform-provider-vcd v2.9.0 with DisableKeepAlives and various TLSHandshakeTimeout/Timeout/MaxRetryTimeout values - these had no effect on the problem.

What apparently solved it is bumping **go-vcloud-director** version in **go.mod** from v2.8.0-beta.2 to **v2.9.0**. With such terraform-provider-vcd v2.9.0 build we have been unable to reproduce the problem.

So I believe the root cause is hidden somewhere https://github.com/vmware/go-vcloud-director/compare/v2.8.0-beta.2...v2.9.0?diff=split and is fixed already in go-vcloud-director v2.9.0.

Testing with newer .tf file and terraform-provider-vcd v3.2.0 we could not reproduce this problem at all.

Thank you @Didainius for looking into this and making that fork that ultimately lead us to this solution.

**Comment by lvirbalas** [comment] 2021-04-22 11:14
@kisstd I hope this means you are upgrading to the latest provider version. We highly recommend that, as v2.9.0 is very old by now :)

**Comment by Didainius** [comment] 2021-04-22 18:23
First of all thanks for getting back and I am happy you have it working, although it would be good to understand what was the cause there.
I have skimmed through this diff and I don't see anything changing in how we use HTTP client. One of bigger changes in this diff was default API version usage bump (31.0 -> 32.0). Although we are discussing lower level operations (HTTP calls here).

I will close this issue with a mystery in there. If you start having this problem again (and especially on latest versions) it would be very interesting to here more.

**Closed by Didainius** 2021-04-22 18:23 UTC
