### ISSUE TITLE
Creating a VM with several disk with terraform vcd but I always get the same error that is rather odd.

### ISSUE THREAD

**Issue by marcusnh** [vmware/terraform-provider-vcd#976] opened 2023-01-04 13:05 UTC
Hello, I have a problem when creating several VMs from a template and adding several disks to that VM.
When I run it the first time I get this error. when I run Terraform apply again it works. If I destroy it and run Terraform apply again, I get the same error. 

### Terraform Version
Terraform v1.2.6
on windows_amd64
+ provider registry.terraform.io/vmware/vcd v3.8.0

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp_vm

### Terraform Configuration Files
```hcl
resource "vcd_vapp_vm" "this" {
  count = var.nr_of_vms
  vapp_name = vcd_vapp.this.name
  name =  "${var.vm_name}${count.index+1}" 
  
  vapp_template_id = data.vcd_catalog_vapp_template.redhat.id
  
  computer_name = "${var.vm_name}${count.index+1}" 
  memory = 4096
  cpus = 2
  cpu_cores = 1

  # Map the network from the data source to the VM
  network {
      name = var.network_name 
      type = "org"
      ip_allocation_mode = "POOL"
      #is_primary = true
  }

 # TODO: change before prod
  customization {
    force                      = true
    auto_generate_password     = false
    admin_password             = "admin"
    # Other customization options to override the ones from template
  }

   depends_on = [vcd_vapp.this]
 }

resource "vcd_vm_internal_disk" "vm1" {
  count = var.nr_of_vms
  vapp_name       = vcd_vapp.this.name
  vm_name         = vcd_vapp_vm.this[0].name
  bus_type        = "paravirtual"
  size_in_mb      = "4096"
  bus_number      = 0
  unit_number     = count.index+1
  #storage_profile = "FC-3PAR-DS-HE"
  allow_vm_reboot = true
  depends_on      = ["vcd_vapp_vm.this"]

}
```

### Debug Output
Please provide a link to GitHub [Gist(s)](https://gist.github.com) containing complete debug
output. You can enable debug by using the commands below:
```shell

│ Error: error setting VM CPU/Memory HotAdd capabilities: error updating VM capabilities section: API Error: 400: [ 335809e7-c4bf-47a2-98bc-6895dd93ef03 ] The entity Ref: com.vmware.vcloud.entity.vm:e1c04e33-3781-45a2-938b-71a19bccbb23 is busy completing an operation VAPP_DEPLOY.
│
│   with vcd_vapp_vm.this[2],
│   on main.tf line 62, in resource "vcd_vapp_vm" "this":
│   62: resource "vcd_vapp_vm" "this" {
│   
```

### Expected Behavior
"Apply complete! Resources:..."

### Actual Behavior
Error with busy completing an operation VAPP_DEPLOY

### Steps to Reproduce
I guess you will need my template. Not sure how to add this
1. `terraform apply`

**Comment by Didainius** [comment] 2023-01-04 13:12
Hello @marcusnh ,
Does this occur only when you have count >1 or does it happen even with a single VM? Does it happen if you don't add the internal disk?

**Comment by marcusnh** [comment] 2023-01-04 13:49
no it works fine with one vm. No changes for 1 or 4 disks

**Comment by Didainius** [comment] 2023-01-04 14:00
What if you don't add disks at all?

**Comment by marcusnh** [comment] 2023-01-04 14:22
If i remove the disks the error occurs on the first VM and not on the last VM as it has done earlier. Very strange behavior..
Here is the full output:
```shell

╷
│ Error: error creating VM from template: [VM creation] error getting VM minio3 : error instantiating a new VM: error instantiating a new VM: API Error: 400: [ 212686f7-e799-45b1-9f17-6b6269876457 ] The entity Ref: com.vmware.vcloud.entity.vapp:a6673c14-93fd-4690-b9f1-0b05621f80c3 is busy completing an operation VAPP_DEPLOY.
│
│   with vcd_vapp_vm.this[2],
│   on main.tf line 63, in resource "vcd_vapp_vm" "this":
│   63: resource "vcd_vapp_vm" "this" {
│
╵
╷
│ Error: error creating VM from template: [VM creation] error getting VM minio1 : error instantiating a new VM: error instantiating a new VM: API Error: 400: [ f2bef03f-3603-432a-9a79-d21335656d89 ] The entity Ref: com.vmware.vcloud.entity.vapp:a6673c14-93fd-4690-b9f1-0b05621f80c3 is busy completing an operation VAPP_DEPLOY.
│
│   with vcd_vapp_vm.this[0],
│   on main.tf line 63, in resource "vcd_vapp_vm" "this":
│   63: resource "vcd_vapp_vm" "this" {
│
╵
╷
│ Error: error setting VM CPU/Memory HotAdd capabilities: error updating VM capabilities section: API Error: 400: [ dbdf42c1-c496-4867-907b-3fdaeddeec1c ] The entity Ref: com.vmware.vcloud.entity.vm:abb66855-3562-471b-ba24-21a320c2a836 is busy completing an operation VAPP_DEPLOY.
│
│   with vcd_vapp_vm.this[3],
│   on main.tf line 63, in resource "vcd_vapp_vm" "this":
│   63: resource "vcd_vapp_vm" "this" {
│
╵
╷
│ Error: error creating VM from template: [VM creation] error getting VM minio2 : error instantiating a new VM: error instantiating a new VM: API Error: 400: [ eecc559f-9bf9-45d0-8675-c6936ce21938 ] The entity Ref: com.vmware.vcloud.entity.vapp:a6673c14-93fd-4690-b9f1-0b05621f80c3 is busy completing an operation VAPP_DEPLOY.
│
│   with vcd_vapp_vm.this[1],
│   on main.tf line 63, in resource "vcd_vapp_vm" "this":
│   63: resource "vcd_vapp_vm" "this" {
│

```

**Comment by Didainius** [comment] 2023-01-04 14:25
Can you try the same by using `-parallelism=1` flag? [-parallelism=n](https://developer.hashicorp.com/terraform/cli/commands/apply#parallelism-n)

**Comment by marcusnh** [comment] 2023-01-04 14:49
Adding the disks again, and running with terraform apply --parallelism=1 did not work FYI.:

│ Error: error creating VM from template: [VM creation] error getting VM minio1 : error instantiating a new VM: error instantiating a new VM: API Error: 400: [ db7d51a3-6c78-46a2-b559-7e7205192467 ] The entity Ref: com.vmware.vcloud.entity.network:72bd0740-12bd-48e7-9381-e73cfb6a8737 is busy completing an operation VAPP_DEPLOY.
│
│   with vcd_vapp_vm.this[0],
│   on main.tf line 52, in resource "vcd_vapp_vm" "this":
│   52: resource "vcd_vapp_vm" "this" {
│
╵
╷
│ Error: error creating VM from template: [VM creation] error getting VM minio4 : error instantiating a new VM: error instantiating a new VM: API Error: 400: [ ef587d2e-e7ba-4165-9843-880d67e3681a ] The entity Ref: com.vmware.vcloud.entity.network:72bd0740-12bd-48e7-9381-e73cfb6a8737 is busy completing an operation VAPP_DEPLOY.
│
│   with vcd_vapp_vm.this[3],
│   on main.tf line 52, in resource "vcd_vapp_vm" "this":
│   52: resource "vcd_vapp_vm" "this" {
│
╵
╷
│ Error: error creating VM from template: [VM creation] error getting VM minio3 : error instantiating a new VM: error instantiating a new VM: API Error: 400: [ 239d03a8-d7fb-4c5d-a36f-e5439a533c5b ] The entity Ref: com.vmware.vcloud.entity.network:72bd0740-12bd-48e7-9381-e73cfb6a8737 is busy completing an operation VAPP_DEPLOY.
│
│   with vcd_vapp_vm.this[2],
│   on main.tf line 52, in resource "vcd_vapp_vm" "this":
│   52: resource "vcd_vapp_vm" "this" {
│
╵
╷
│ Error: error setting VM CPU/Memory HotAdd capabilities: error updating VM capabilities section: API Error: 400: [ cad10722-70c7-4fd1-bcfd-fda1b4154681 ] The entity Ref: com.vmware.vcloud.entity.vm:ee5d46be-4f1a-402e-9c99-178771d15764 is busy completing an operation VAPP_DEPLOY.
│
│   with vcd_vapp_vm.this[1],
│   on main.tf line 52, in resource "vcd_vapp_vm" "this":
│   52: resource "vcd_vapp_vm" "this" {

**Comment by Didainius** [comment] 2023-01-05 12:34
@marcusnh ,
May I also ask you to try it with provider `v3.7.0`? I want to understand if this is a 3.8.X regression or not.

**Comment by marcusnh** [comment] 2023-01-06 10:39
With the provider v3.7.0 I have the same problem as before. Had to change my code to this:

```yaml

########################################################################################
###                    Provisioning resources                                            ###
########################################################################################

# Create the vApp if it is not already created
resource "vcd_vapp" "this" {
  name = var.vapp_name # required
  org  = var.vcd_org  # required unless defined at provider level
  vdc  = var.vdc_name  # required unless defined at provider level
}


# Connect the dedicated routed network to vApp
resource "vcd_vapp_org_network" "network" {
  #count =  data.vcd_network_routed_v2.this.id == null  ? 1 : 0
  count = var.network_name== "" ? 0 : 1
  vapp_name        = vcd_vapp.this.name
  org_network_name = var.network_name

  # It's a pre-requisite for configuring Firewall and NAT rules per vApp
  is_fenced = false

  depends_on = [vcd_vapp.this]
}


resource "vcd_vapp_vm" "this" {
  count = var.nr_of_vms
  vapp_name = vcd_vapp.this.name
  name =  "${var.vm_name}${count.index+1}" 
  
  # vapp_template_id = data.vcd_catalog_vapp_template.redhat.id
  template_name = var.template_name
  catalog_name = var.catalog_name
  
  computer_name = "${var.vm_name}${count.index+1}" 
  # memory = 4096
  # cpus = 2
  # cpu_cores = 1

  # Map the network from the data source to the VM
  network {
      name = var.network_name #data.vcd_network_routed.net.name
      type = "org"
      ip_allocation_mode = "POOL"
      #is_primary = true
  }

  customization {
    force                      = false
    auto_generate_password     = false
    admin_password             = "admin"
    # Other customization options to override the ones from template
  }

 # TODO: change before prod
# # check with cloud admin beforehand
#   metadata_entry{
#     linux_baseconfig = "No"
#   }


   depends_on = [vcd_vapp.this, vcd_vapp_org_network.network]
 }

resource "vcd_security_tag" "this" {
  name   = "minio-test"
  vm_ids = vcd_vapp_vm.this[*].id

  depends_on = [
    vcd_vapp_vm.this
  ]
}


resource "vcd_vm_internal_disk" "disk1" {
  count = var.nr_of_vms
  vapp_name       = vcd_vapp.this.name
  vm_name         = vcd_vapp_vm.this[count.index].name
  bus_type        = "paravirtual"
  size_in_mb      = "4096"
  bus_number      = 0
  unit_number     = 1
  #storage_profile = "FC-3PAR-DS-HE"
  allow_vm_reboot = true
  depends_on      = [vcd_vapp_vm.this]
}

resource "vcd_vm_internal_disk" "disk2" {
  count = var.nr_of_vms
  vapp_name       = vcd_vapp.this.name
  vm_name         = vcd_vapp_vm.this[count.index].name
  bus_type        = "paravirtual"
  size_in_mb      = "4096"
  bus_number      = 0
  unit_number     = 2
  #storage_profile = "FC-3PAR-DS-HE"
  allow_vm_reboot = true
  depends_on      = [vcd_vapp_vm.this]
}

resource "vcd_vm_internal_disk" "disk3" {
  count = var.nr_of_vms
  vapp_name       = vcd_vapp.this.name
  vm_name         = vcd_vapp_vm.this[count.index].name
  bus_type        = "paravirtual"
  size_in_mb      = "4096"
  bus_number      = 0
  unit_number     = 3
  #storage_profile = "FC-3PAR-DS-HE"
  allow_vm_reboot = true
  depends_on      = [vcd_vapp_vm.this]
}

resource "vcd_vm_internal_disk" "disk4" {
  count = var.nr_of_vms
  vapp_name       = vcd_vapp.this.name
  vm_name         = vcd_vapp_vm.this[count.index].name
  bus_type        = "paravirtual"
  size_in_mb      = "4096"
  bus_number      = 0
  unit_number     = 4
  #storage_profile = "FC-3PAR-DS-HE"
  allow_vm_reboot = true
  depends_on      = [vcd_vapp_vm.this]
}

```

# output:

```
vcd_vapp_vm.this[2]: Still creating... [7m10s elapsed]
vcd_vapp_vm.this[3]: Still creating... [7m10s elapsed]
vcd_vapp_vm.this[2]: Still creating... [7m20s elapsed]
vcd_vapp_vm.this[3]: Still creating... [7m20s elapsed]
╷
│ Error: error changing memory size: task did not complete successfully:  [400:BAD_REQUEST] - [ 6fde3328-d48c-4037-86c9-f395e103ff7b ] The virtual machine memory size must be positive.
│
│   with vcd_vapp_vm.this[1],
│   on main.tf line 52, in resource "vcd_vapp_vm" "this":
│   52: resource "vcd_vapp_vm" "this" {
│
╵
╷
│ Error: error changing memory size: task did not complete successfully:  [400:BAD_REQUEST] - [ b06c7edf-1109-480f-b83b-b72da49da086 ] The virtual machine memory size must be positive.
│
│   with vcd_vapp_vm.this[0],
│   on main.tf line 52, in resource "vcd_vapp_vm" "this":
│   52: resource "vcd_vapp_vm" "this" {
│
╵
╷
│ Error: [VM creation] error adding VM: error instantiating a new VM: API Error: 500: [ e640ea50-ccf7-4a43-bc65-91df2ec9a4a1 ] Unable to perform this action. Contact your cloud administrator.
│
│   with vcd_vapp_vm.this[3],
│   on main.tf line 52, in resource "vcd_vapp_vm" "this":
│   52: resource "vcd_vapp_vm" "this" {
│
╵
╷
│ Error: error changing memory size: task did not complete successfully:  [400:BAD_REQUEST] - [ af08899e-fcca-421f-8980-e187f80b1ebb ] The virtual machine memory size must be positive.
│
│   with vcd_vapp_vm.this[2],
│   on main.tf line 52, in resource "vcd_vapp_vm" "this":
│   52: resource "vcd_vapp_vm" "this" {
│
```


In my VCD setup 3 out of 4 VMs have come online, but I have experienced that there can be some problems with their setup

**Comment by Didainius** [comment] 2023-01-06 11:36
Thanks - I will attempt to this once more. I was not able to trigger such error based on your previous example.

Additionally, 
Could I ask you to enable logging and share some logs as per the doc here https://github.com/vmware/terraform-provider-vcd/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md#debug-output

Double check the go-vcloud-director.log  and obfuscate anything you want (like `hostname`) by using search and replace. Credentials should be masked by default.

**Comment by marcusnh** [comment] 2023-01-09 09:31
Here are the logs that you requested: https://gist.github.com/marcusnh/583bc40dd46e6350f25055bd96af29f7
It stops on the last VM, as it has done previously. This is done with:
```
Terraform v1.2.6
on windows_amd64
+ provider registry.terraform.io/vmware/vcd v3.7.0
```
The error I received while running this time was similar as shown above:
```
 Error: error changing memory size: error updating VM spec section: API Error: 400: [ c72d8f5e-7aa0-4059-9e97-9ab8abbba493 ] The entity Ref: com.vmware.vcloud.entity.vm:a65b2036-80c9-4965-a8c3-54f4fcf80ad2 is busy completing an operation VAPP_DEPLOY.
│
│   with vcd_vapp_vm.this[0],
│   on main.tf line 52, in resource "vcd_vapp_vm" "this":
│   52: resource "vcd_vapp_vm" "this" {
│
╵
╷
│ Error: error changing memory size: error updating VM spec section: API Error: 400: [ 414d731a-1ce4-4d3e-a96a-dd283800e932 ] The entity Ref: com.vmware.vcloud.entity.vm:a23b8114-31dc-448c-9e6c-eacfbcf9af3b is busy completing an operation VAPP_DEPLOY.
│
│   with vcd_vapp_vm.this[1],
│   on main.tf line 52, in resource "vcd_vapp_vm" "this":
│   52: resource "vcd_vapp_vm" "this" {
│
╵
```

There is something in the VM template or the fact that our private cloud is changing the guest properties that interferes with the creation of the VMs. I would greatly appreciate any feedback you can give me.

**Comment by Didainius** [comment] 2023-01-09 09:58
> There is something in the VM template or the fact that our private cloud is changing the guest properties that interferes with the creation of the VMs.

Curious to know about this more - do regular VM templates work fine for you?

**Comment by marcusnh** [comment] 2023-01-09 10:21
Or I'm not sure if this is the reason, but that is my initial thought.  I'm setting a security tag to all of the vms that is being created so that changes the guest properties, but that should not give that error. With other templates, I still get the same error. What do you mean with a " regular VM templates"?

**Comment by marcusnh** [comment] 2023-01-16 13:41
The problem is possible with my underlying system and my use of security tags for implementing processes when VMs are being created. I can solve this problem if I can get existing security tags (data.vcd_security_tag) and connect my VM to them before creating them. Why doesn't there exist a Data vcd_security_tag?

**Comment by marcusnh** [comment] 2023-01-16 13:45
Similar as this [request]( https://github.com/vmware/terraform-provider-vcd/issues/894)

**Comment by Didainius** [comment] 2023-01-16 13:46
> The problem is possible with my underlying system and my use of security tags for implementing processes when VMs are being created. I can solve this problem if I can get existing security tags (data.vcd_security_tag) and connect my VM to them before creating them. Why doesn't there exist a Data vcd_security_tag?

Hi. I struggle to understand the root cause of the problem yet. Would you be able to probably share a bigger snippet, which contains your problem and how this could be solved with a `vcd_security_tag` data source? The problem with data source for the security tag was that you cannot create an empty security tag (API does not allow this). It must have at least one VM assigned upon creation.

**Comment by marcusnh** [comment] 2023-01-16 13:56
Thank you for your message. I'm not 100% confident that this is the root cause, but I believe that the problem is the security tag. I use two security tags. One tag to set up specific firewall configurations. This one is configured to all VMs created in my VDC automatically. The other I created in my Terraform code allows communication between these VMs.  Therefore if I can pre-assign the first security tag I can perhaps avoid the issue where the vcd tries to enforce changes while the VMs are being deployed with terraform.

**Comment by Didainius** [comment] 2023-07-25 08:07
Hello @marcusnh ,
Did you overcome this issue? Maybe assigning security tags at VM level could help you? https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vapp_vm#security_tags

I am closing this for now, but feel free to add comments and reopen if if needed

**Closed as completed by Didainius** 2023-07-25 08:07 UTC
