### ISSUE TITLE
Cannot get multiple external network

### ISSUE THREAD

**Issue by khayama** [vmware/terraform-provider-vcd#577] opened 2020-10-21 14:16 UTC
### Terraform Version
```
% terraform -v
Terraform v0.13.4
+ provider registry.terraform.io/-/vcd v3.0.0
+ provider registry.terraform.io/vmware/vcd v3.0.0
```

### Affected Resource(s)
- vcd_edgegateway
- external_network

### Terraform Configuration Files
```hcl
variable vcd_edge {}

data "vcd_edgegateway" "mygw" {
  name = var.vcd_edge
  org  = var.vcd_org
  vdc  = var.vcd_vdc
}

output "external_network" {
  value = data.vcd_edgegateway.mygw.external_network
}
output "external_network_ips" {
  value = data.vcd_edgegateway.mygw.external_network_ips
}
.
```

### Output 1
We have got the different output for each execution when we have multiple external network

```
Outputs:

external_network = [
  {
    "enable_rate_limit" = false
    "incoming_rate_limit" = 0
    "name" = "fra04-w02-tenant-external"
    "outgoing_rate_limit" = 0
    "subnet" = [
      {
        "gateway" = "161.156.x.x"
        "ip_address" = ""
        "netmask" = "255.255.255.0"
        "suballocate_pool" = [
          {
            "end_address" = "161.156.x.x"
            "start_address" = "161.156.x.x"
          },
        ]
        "use_for_default_route" = true
      },
    ]
  },
]
external_network_ips = [
  "161.156.x.x",
  "52.117.x.x",
]

```

### Output 2
We have got the different output for each execution when we have multiple external network

```
Outputs:

external_network = [
  {
    "enable_rate_limit" = false
    "incoming_rate_limit" = 0
    "name" = "fra04-w02-service01"
    "outgoing_rate_limit" = 0
    "subnet" = [
      {
        "gateway" = "52.117.x.x"
        "ip_address" = ""
        "netmask" = "255.255.255.0"
        "suballocate_pool" = []
        "use_for_default_route" = false
      },
    ]
  },
]
external_network_ips = [
  "161.156.x.x",
  "52.117.x.x",
]

```

**Comment by Didainius** [comment] 2020-10-22 05:58
Hello @khayama ,
This is a Terraform core issue (https://github.com/hashicorp/terraform-plugin-sdk/pull/197) which potentially may be resolved or not when we move to version 2 of Terraform SDK. We are reviewing it.


As for your problem - what is your end goal? Maybe datasources `vcd_external_network` or `vcd_external_network_v2` could help here?

**Comment by khayama** [comment] 2020-10-23 02:15
I would like to get just the multiple external networks correctly at one time.

Do you have any code example to get data `vcd_external_network_v2`?
The following link looks not enough for me.
https://registry.terraform.io/providers/vmware/vcd/latest/docs/data-sources/external_network_v2

**Comment by Didainius** [comment] 2020-10-23 04:27
@khayama,
What exactly do you miss? Is it the structure? Structure of this data source would be exactly the same as the resource itself uses (https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/external_network_v2). It has only `name` field because it does the lookup by name.
Now the question is if you are working at provider or tenant level. I guess external networks are only available to provider.

**Comment by khayama** [comment] 2020-10-23 05:43
@Didainius  I have got this error.  Is this because I don't have vCenter admin role?

```
Error: Unsupported attribute

  on data_vcd_edgegateway.tf line 13, in output "external_network":
  13:   value = data.vcd_edgegateway.mygw.external_network_v2

This object has no argument, nested block, or exported attribute named
"external_network_v2".
```

Anyway I would like to get just the multiple external networks correctly at one time like

```
external_network = [
  {
    "enable_rate_limit" = false
    "incoming_rate_limit" = 0
    "name" = "fra04-w02-tenant-external"
    "outgoing_rate_limit" = 0
    "subnet" = [
      {
        "gateway" = "161.156.x.x"
        "ip_address" = ""
        "netmask" = "255.255.255.0"
        "suballocate_pool" = [
          {
            "end_address" = "161.156.x.x"
            "start_address" = "161.156.x.x"
          },
        ]
        "use_for_default_route" = true
      },
    ]
  },
  {
    "enable_rate_limit" = false
    "incoming_rate_limit" = 0
    "name" = "fra04-w02-service01"
    "outgoing_rate_limit" = 0
    "subnet" = [
      {
        "gateway" = "52.117.x.x"
        "ip_address" = ""
        "netmask" = "255.255.255.0"
        "suballocate_pool" = []
        "use_for_default_route" = false
      },
    ]
  }
]
```

**Comment by Didainius** [comment] 2020-10-23 05:47
@khayama,
The `vcd_external_network_v2` is a resource (and datasource) itself while you are trying to refer to it inside edge gateway data source.

You should have something like this:

```hcl
data "vcd_external_network_v2" "first-net" {
    name = "fra04-w02-tenant-external"
}

data "vcd_external_network_v2" "second-net" {
    name = "fra04-w02-service01"
}
```
Provided you have sufficient rights. (provider access)


Still probably I would ask - what is the end goal. What are you trying to achieve?

**Comment by khayama** [comment] 2020-10-23 05:57
@Didainius Okay, I seem not to have admin access.
Actually I'm acting as tenant user at moment.

>what is the end goal. What are you trying to achieve?

 I would like to get just the multiple external networks datasource correctly at one time like

```
external_network = [
  {
    "enable_rate_limit" = false
    "incoming_rate_limit" = 0
    "name" = "fra04-w02-tenant-external"
    "outgoing_rate_limit" = 0
    "subnet" = [
      {
        "gateway" = "161.156.x.x"
        "ip_address" = ""
        "netmask" = "255.255.255.0"
        "suballocate_pool" = [
          {
            "end_address" = "161.156.x.x"
            "start_address" = "161.156.x.x"
          },
        ]
        "use_for_default_route" = true
      },
    ]
  },
  {
    "enable_rate_limit" = false
    "incoming_rate_limit" = 0
    "name" = "fra04-w02-service01"
    "outgoing_rate_limit" = 0
    "subnet" = [
      {
        "gateway" = "52.117.x.x"
        "ip_address" = ""
        "netmask" = "255.255.255.0"
        "suballocate_pool" = []
        "use_for_default_route" = false
      },
    ]
  }
]
```

Do you have any solution above?

**Comment by Didainius** [comment] 2020-10-23 06:17
Sadly I think I don't know how to achieve that for now because of Terraform core limitation. What data exactly do you need and where do you want to use this data?

**Comment by Didainius** [comment] 2020-10-23 06:18
If you need to refer some of this data in some other resource - we might have some way around it, but need to understand what is your use case

**Comment by Didainius** [comment] 2020-10-27 07:18
Confirmed. Once #576 is merged and this provider used terraform SDK v2 - datasources do not have collapsed TypeSets anymore.

**Comment by Didainius** [comment] 2020-11-19 07:06
Closing as the next version will solve it.

**Closed by Didainius** 2020-11-19 07:06 UTC

**Comment by khayama** [comment] 2021-01-15 01:26
I have confirmed it works now with this version config, thanks.

```
terraform {
  required_version = ">= 0.13"
  required_providers {
    vcd = {
      source  = "vmware/vcd"
      version = ">= 3.1"
    }
  }
}
```
